import type { ArticleImages } from './content';

// Generated by pipeline/build_images.py — one entry per article that has
// at least one image, keyed by the same content id the article collection
// uses. Re-run that script after any content pipeline change.
import manifest from '../../../content/_images.json';

const data = manifest as Record<string, ArticleImages>;

export function getArticleImages(id: string): ArticleImages | null {
  return data[id] ?? null;
}
